# Generated by Django 4.2.3 on 2023-07-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_names', models.CharField(max_length=100)),
                ('buyer_contact', models.CharField(max_length=100)),
                ('bought_part', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('number_of_items_taken', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('arrival_date', models.DateField()),
                ('total_initial_stock_quantity', models.IntegerField()),
                ('country_of_origin', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
